---

- name: copy demo
  hosts: all  # ....
  tasks:
    - name: copy resolv.conf
      copy:
        src: files/resolv.conf
        dest: /tmp/resolv.conf
        force: yes

    - debug:
        msg: "my name is: {{myname}}, age is {{age}}"
      when:
      - myname is defined
      - age is defined
