---
- name: Linux System Health Check 
  hosts: all
  roles:
    - { role: workflows/system_health_check }
   
- name: export to excel file
  hosts: localhost
  roles:
    - { role: atomics/export2excel, type: cc }
  
