---
- name: Linux System Health Check 
  ignore_errors: True
  ignore_unreachable: True
  hosts:  all
  tasks:
  - name: set resource name
    set_fact:
      res_check_type: health_check 

  roles:
    - { role: workflows/system_health_check }
  
   
- name: export to excel file
  hosts: localhost # 10.72.93.134
  roles:
    - { role: atomics/export2excel, type: hc }

