---

- name: copy demo
  hosts: all  # ....
  tasks:
    - name: copy resolv.conf
      copy:
        content: |
          nameserver 114.114.114.114
          nameserver 8.8.8.8 
        dest: /tmp/resolv.conf
        force: yes
