---
- name: Run tasks on local and remote hosts
  hosts: localhost  # ....
  tasks:
    - name: Create directory on local host
      file:
        path: /tmp/dns
        state: directory

- name: Run tasks on local and remote hosts
  hosts: all  # ....
  tasks:
    - name: Fetch /etc/resolv.conf
      fetch:
        src: /etc/resolv.conf
        dest: "/tmp/dns/{{ inventory_hostname }}_resolv.conf"
        flat: yes

