---
- name: file demo
  gather_facts: false
  hosts: bastion
  tasks:
  - name: crate a dir
    file:
      path: "{{path}}"
      state: directory
    tags: 
    - dir
    - never
    
  - name: crate a file
    file:
      path: "{{path}}"
      state: touch
    tags: 
    - file
    - never

  - name: delete file or dir
    file:
      path: "{{path}}"
      state: absent
    tags: 
    - remove
    - never
  
