---
- name: file demo
  gather_facts: false
  hosts: 127.0.0.1
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: /tmp/training
      state: directory
      mode: '0755'
    
 
