---
- name: file demo
  gather_facts: false
  hosts: bastion
  tasks:
  - name: crate a dir
    file:
      path: "{{path}}"
      state: directory
   
  - name: crate a file
    file:
      path: "{{path}}"
      state: touch

  - name: delete file or dir
    file:
      path: "{{path}}"
      state: absent
    
 
