---
- name: script demo
  hosts: bastion
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: run test script
    script: files/test.sh
  #- name: run failed script
  #  script: files/test2.sh
