---
- name: command demo
  hosts: bastion
  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: present

  - name: correct httpd.conf is present
    copy:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify: 
      - restart httpd

  - name: httpd is started
    service:
      name: httpd
      state: started 
      enabled: true
  
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
    
 
