---
- name: command demo
  hosts: bastion
  tasks:
  #- name: httpd package is present
  #  yum:
  #    name: httpd
  #    state: present

  - name: correct httpd.conf is present
    copy:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf

  - name: httpd is started
    service:
      name: httpd
      state: restarted #change to restarted to test
      enabled: true
  
 
    
 
