---
- name: template demo
  hosts: bastion
  gather_facts: true
  tasks:
  - name: auto hosts file from template
    template:
      src: hosts.j2
      dest: /tmp/hosts
      owner: root
      group: root
      mode: 0644
  - name: show facts
    debug:
      msg: "{{hostvars[inventory_hostname]['ansible_hostname']}}"



