---
- name: yum demo
  gather_facts: false
  hosts: bastion
  tasks:

  - name: httpd is installed
    yum:
      name: httpd
      state: present
  
  - name: httpd-tools is installed
    yum:
      name: httpd-tools
      state: present
  
  - name: httpd-filesystem is installed
    yum:
      name: httpd-filesystem
      state: present
 
    
 
