---
- name: import tasks demo
  hosts: bastion
  gather_facts: false
  ignore_errors: true
  tasks:
  #- import_tasks: playbooks/disable-selinux.yaml
  - import_tasks: playbooks/stop-firewalld.yaml
  - import_tasks: playbooks/httpd-install.yaml





