---
- hosts: bastion
  force_handlers: yes
  tasks:
  - name: a task which always notifies its handler
    command: /bin/true
    notify: restart the service
  
  - name: a task which fails because the package doesn't exist
    yum:
      name: notapkg
      state: latest
  
  handlers:
  - name: restart the service
    service:
      name: httpd
      state: restarted
