---
- hosts: all
  ignore_errors: true
  ignore_unreachable: true
  tasks:
  - name: find files
    shell: ls /root|grep TTTTTT
    register: res_result
  - name: show find result
    debug:
      msg: "{{res_result}}"


