---
- hosts: all
#  remote_user: root
#  become: yes

  tasks:
  - debug:
      msg:
      - "ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
      - "major version: {{ ansible_distribution_major_version }}"
      - "version: {{ ansible_distribution_version }}"
