- name: Test privilege escalation
  hosts: 127.0.0.1
  #become: yes
  #become_method: sudo
  tasks:
    - name: Ensure a file exists with root privileges
      file:
        path: /etc/test.conf
        state: touch
      #become: yes
